#page title
page_title                                : Flutter Tips                              # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6482293361                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.codewithandrea.flutter_tips_and_tricks                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/app-icon.png                       # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Flutter Tips                              # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Bite-sized tips about Flutter             # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A curated collection of bite-sized tips and tricks for Flutter app development.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

canonical_url                             : https://fluttertips.dev
og_image                                  : https://fluttertips.dev/assets/social-media-banner.png

# Information About Yourself
your_name                                 : Andrea Bizzotto
your_link                                 : https://codewithandrea.com                     
your_city                                 :                     
email_address                             : contact@codewithandrea.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : biz84
github_username                           : bizz84
youtube_username                          : CodeWithAndrea
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Over 150 Tips
    description                           : Browse over 150 tips and tricks about Dart and Flutter app development.
    fontawesome_icon_name                 : hashtag
    
  - title                                 : Search Feature
    description                           : Search existing tips or choose a random tip.
    fontawesome_icon_name                 : search

  - title                                 : Offline mode
    description                           : Downloaded tips are saved locally so you can access them even when you don't have a network connection.
    fontawesome_icon_name                 : wifi

  - title                                 : Image Viewer
    description                           : Tap, pinch and zoom on any image for better ease of use.
    fontawesome_icon_name                 : search-plus

  - title                                 : Light/dark mode
    description                           : Choose your favorite theme or let the app automatically adjusts to the system theme.
    fontawesome_icon_name                 : moon

  - title                                 : Additional Resources
    description                           : Get access to additional resources, articles and videos about Flutter, right from the app.
    fontawesome_icon_name                 : newspaper



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : blue                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#285C99"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#285C99"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
